apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: yeogiyo-shop-deployment
  labels:
    app: yeogiyo-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yeogiyo-shop
  template:
    metadata:
      labels:
        app: yeogiyo-shop
    spec:
      containers:
        - name: yeogiyo-shop
          image: gcr.io/yeogiyo/yeogiyo-shop:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8087
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: yeogiyo-shop
  name: yeogiyo-shop-service
  namespace: default
spec:
  ports:
    - port: 8087
      protocol: TCP
      targetPort: 8087
  selector:
    app: yeogiyo-shop
  type: LoadBalancer