apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: yeogiyo-order-deployment
  labels:
    app: yeogiyo-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yeogiyo-order
  template:
    metadata:
      labels:
        app: yeogiyo-order
    spec:
      containers:
        - name: yeogiyo-order
          image: gcr.io/yeogiyo/yeogiyo-order:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: yeogiyo-order
  name: yeogiyo-order-service
  namespace: default
spec:
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: yeogiyo-order
  type: LoadBalancer