apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: yeogiyo-menu-deployment
  labels:
    app: yeogiyo-menu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yeogiyo-menu
  template:
    metadata:
      labels:
        app: yeogiyo-menu
    spec:
      containers:
        - name: yeogiyo-menu
          image: gcr.io/yeogiyo/yeogiyo-menu:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: yeogiyo-menu
  name: yeogiyo-menu-service
  namespace: default
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: yeogiyo-menu
  type: LoadBalancer