server:
  port: 8087  # Spring boot Server port

spring:
  h2:
    console:
      enabled: true  # H2 웹 콘솔을 사용하겠다는 의미
      path: /db  # 콘솔의 경로
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:yeogiyoshop;AUTO_SERVER=TRUE
#    username: yeogiyoshop
#    password: yeogiyoshop
